### ISSUE TITLE
index overrun in create_keys()

### ISSUE THREAD

**Issue by delhatch** [dmandalidis/des#1]
Thank you for this code.
I found one little bug in create_keys():
   In the first "for" loop, the index increments from 0 to 16, but the erot array max's at erot[15].
Changing the index to stop at 15 fixes the problem.
   Old: for (i = 0; i < 17; i++)
   New: for (i = 0; i < 16; i++)
Thank you again!

**Comment by dmandalidis** [comment]
Hi @delhatch,

You 're right there is indeed such overrun. However, I would take me some time to fix it since it's a 10yrs old code and I can hardly remember how this is supposed to work :) I don't intend to leave it unfixed but it will take me some time. Sorry for this.

**Comment by delhatch** [comment]
Haha. No problem. With that one little change it works perfectly. Thanks again!
